app = 'f1-telemetry-ui'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[env]
  BACKEND_URL = 'https://f1-telemetry-api.fly.dev'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
